# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Targumia
email: targumia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Targumia es el primer proyecto que busca dar herramientas para independizarse de las traducciones
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://targumia.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
